// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnYFatwYmKgKBll8Zi-LR7F1KFtcZ_emY',
    appId: '1:80036771560:web:14eb1e8a0ee413908a7b5d',
    messagingSenderId: '80036771560',
    projectId: 'fir-strideup',
    authDomain: 'fir-strideup.firebaseapp.com',
    storageBucket: 'fir-strideup.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB05KAqbvrlXDEkWp33Fgxl-naqT1zizDY',
    appId: '1:80036771560:android:b31701d28b12ad798a7b5d',
    messagingSenderId: '80036771560',
    projectId: 'fir-strideup',
    storageBucket: 'fir-strideup.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoGIBwLcDAsrCh__uA4FPBxvoboA1XpoQ',
    appId: '1:80036771560:ios:653d4d378468c5938a7b5d',
    messagingSenderId: '80036771560',
    projectId: 'fir-strideup',
    storageBucket: 'fir-strideup.firebasestorage.app',
    iosBundleId: 'com.example.strideupFitnessApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoGIBwLcDAsrCh__uA4FPBxvoboA1XpoQ',
    appId: '1:80036771560:ios:653d4d378468c5938a7b5d',
    messagingSenderId: '80036771560',
    projectId: 'fir-strideup',
    storageBucket: 'fir-strideup.firebasestorage.app',
    iosBundleId: 'com.example.strideupFitnessApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnYFatwYmKgKBll8Zi-LR7F1KFtcZ_emY',
    appId: '1:80036771560:web:1f8b1491408b73038a7b5d',
    messagingSenderId: '80036771560',
    projectId: 'fir-strideup',
    authDomain: 'fir-strideup.firebaseapp.com',
    storageBucket: 'fir-strideup.firebasestorage.app',
  );

}